export const UPDATE_SYMBOLS = 'UPDATE_SYMBOLS'
export const UPDATE_SORT = 'UPDATE_SORT'
export const UPDATE_SYMBOLS_API_PROGRESS = 'UPDATE_SYMBOLS_API_PROGRESS'
export const UPDATE_SYMBOL_ERROR = 'UPDATE_SYMBOL_ERROR'
 